before:
  hooks:
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64
    - arm
  goarm:
    - 7
  ignore:
    - goos: windows
      goarch: arm
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: x86_32
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}'
  homepage:  https://github.com/axxelG/loxwebhook
  description: Make selected Loxone inputs and outputs securely available on the internet
  maintainer: Axel Gluth <mail@axelgluth.de>
  vendor: Axel Gluth
  license: LGPL-3.0
  formats:
  - deb
  bindir: "/usr/local/bin/loxwebhook/"
  config_files:
    "./config.example.toml": "/etc/loxwebhook/config.toml"
  empty_folders:
    - "/etc/loxwebhook/controls.d"
  files:
    "./install/systemd_loxwebhook.service": "/etc/systemd/system/loxwebhook.service"
  scripts:
    preinstall: "./install/deb_preinstall.sh"
    postinstall: "./install/deb_postinstall.sh"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
