# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64
    - arm
  goarm:
    - 5
  ignore:
    - goos: windows
      goarch: arm
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: x86_32
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
