logfile = ''
ListenPort = 80
PublicURI = 'example.example.com'
LetsencryptCache = './cache/letsencrypt/example'
ControlsFiles = './controls_example.d'
MiniserverURL = 'http://192.168.1.2:80'
MiniserverUser = 'user'
MiniserverPassword = 'SecretPassword'
MiniserverTimeout = 2 # Seconds