PublicURI = 'loxwebhook.example.com'
ListenPort = 4443
MiniserverURL = 'http://192.168.1.1:80'
MiniserverUser = 'loxwebhook'
MiniserverPassword = 'YourSecretPassword'
MiniserverTimeout = 2 # Seconds
LetsencryptCache = '/home/loxwebhook/loxwebhook/cache/letsencrypt'
logfileMain = '/var/log/loxwebhook/loxwebhook.log'
logfileHTTPError = '/var/log/loxwebhook/error.log'
logfileHTTPAccess = '/var/log/loxwebhook/access.log'
controlsFiles = '/etc/loxwebhook/controls.d'